import Head from "next/head";
import { PostCard } from "~/components/molecules/post-card";

import { api } from "~/utils/api";

export default function Home() {
  const {
    data: posts,
    error,
    isError,
    isLoading,
  } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="@container">
        <div className="mx-auto my-6 w-full max-w-lg">
          <ul className="space-y-5">
            {posts?.map((post) => (
              <li key={post.id}>
                <PostCard
                  content={post.content}
                  authorId={post.authorId}
                  createdAt={post.createdAt}
                />
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}

// function AuthShowcase() {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined },
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// }
